### PR TITLE
Add a toggle button for the info panel.

### PR DESCRIPTION
**Pull request by xuhdev**

### CODE REVIEW

**Comment by IanDCarroll** [comment]
Huzzah!
@benjaminma, @xuhdev could one of you write a blog post about the experience? Here's an example: http://developingian.com/pairing-on-a-map-page/

**Comment by xuhdev** [comment]
Sure, will do it sometime....

**Comment by xuhdev** [comment]
@IanDCarroll The post is now ready [here](https://www.topbug.net/blog/2016/08/27/optimization-for-mobile-a-pair-programming-story-at-fullstackla/)...

**Comment by IanDCarroll** [comment]
This is great! Thanks so much! It's going in the docs and shared with the rest of the FullStack LA crew!

**Pull request merged**
